### ISSUE TITLE
Question about collected data

### ISSUE THREAD

**Issue by fabiuz7** [jamesbarnett91/tplink-energy-monitor#8]
Hi James, thanks for your work. 

Reading your documentation I've have one doubt: where are the data stored?
I mean, I know that TPLink HS110 can store some data, but I was wondering if you have used another mechanism (i.e. a database) to increase the data frequency (I would collect data every 10 seconds or less) and the time span (I would collect over data over months and maybe years).
This could be useful for further investigation about power consuption.

**Comment by fabiuz7** [comment]
Exactly what I need to know! Thank you very much for the explanation.

**Comment by slvrscoobie** [comment]
Is there a way to pull that Monthly data down to export it to excel? id love to have the Daily records of power usage to log against temps for my freezer and heater.. but running the console seems to slow my network down (noticed a significant number of re-requests and sluggishness with my KASA app since starting it.) Id love to be able to log in once a month, capture the previous 30 days data for both devices and put them in an XLS or JSON file to record keeping.
